# Generated by Django 2.2.7 on 2019-11-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='reg_type',
            field=models.CharField(choices=[('user', 'user'), ('redactor', 'redactor')], db_index=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.CharField(choices=[('system', 'system'), ('client', 'client')], db_index=True, default='client', max_length=12),
        ),
    ]
